using System;
using System.Text;
using MphRead.Entities;

namespace MphRead.Mods.Network
{
    /// <summary>
    /// Prints the game's own tables as markdown: `MphRead -mechanics`.
    ///
    /// Written as a dump of the live data rather than as a hand-kept document,
    /// because a hand-kept one is wrong the moment anybody edits a table and
    /// nobody notices. Everything here is read out of Weapons.cs, Metadata and
    /// the damage code at runtime, so it cannot drift from what the game does.
    ///
    /// The rules that are expressed as code rather than as a table -- the
    /// Imperialist's zoom penalty, double damage, the difficulty multiplier --
    /// are listed with the file and line they live in, so the claim can be
    /// checked rather than believed.
    /// </summary>
    public static class MechanicsDump
    {
        public static void Run()
        {
            var text = new StringBuilder();
            text.AppendLine("# Metroid Prime Hunters — multiplayer mechanics");
            text.AppendLine();
            text.AppendLine("Generated by `MphRead -mechanics` from the game's own tables.");
            text.AppendLine();
            Weapons(text);
            DamageRules(text);
            Hunters(text);
            Movement(text);
            States(text);
            SpawnRules(text);
            Modes(text);
            World(text);
            Items(text);
            Bots(text);
            Networking(text);
            Console.Write(text.ToString());
        }

        private static void Weapons(StringBuilder text)
        {
            text.AppendLine("## Weapons (multiplayer table)");
            text.AppendLine();
            text.AppendLine("Damage is per shot before any multiplier. \"Charged\" is a full charge; "
                + "\"min\" is the smallest charge that counts as charged.");
            text.AppendLine();
            text.AppendLine("| Beam | dmg | min-chg | charged | headshot | hs charged | splash | "
                + "ammo | cost | cooldown | afflictions | notes |");
            text.AppendLine("|---|---|---|---|---|---|---|---|---|---|---|---|");
            // The table holds each weapon twice: entries 0-8 are the plain
            // versions and 9-17 the affinity ones, which is how
            // `Weapons.Current[(int)beam + 9]` picks the stronger variant for
            // the hunter the weapon belongs to.
            for (int i = 0; i < MphRead.Weapons.WeaponsMP.Count && i < 18; i++)
            {
                WeaponInfo weapon = MphRead.Weapons.WeaponsMP[i];
                if (weapon.Beam < BeamType.PowerBeam || weapon.Beam > BeamType.OmegaCannon)
                {
                    continue;
                }
                if (i == 9)
                {
                    text.AppendLine();
                    text.AppendLine("Affinity versions -- what a hunter gets when it carries its own "
                        + "weapon. Note the extra damage and the afflictions the plain versions "
                        + "do not have:");
                    text.AppendLine();
                    text.AppendLine("| Beam | dmg | min-chg | charged | headshot | hs charged | splash | "
                        + "ammo | cost | cooldown | afflictions | notes |");
                    text.AppendLine("|---|---|---|---|---|---|---|---|---|---|---|---|");
                }
                var notes = new StringBuilder();
                void Note(string value)
                {
                    if (notes.Length > 0)
                    {
                        notes.Append(", ");
                    }
                    notes.Append(value);
                }
                if (weapon.Flags.TestFlag(WeaponFlags.CanZoom)) Note("can zoom");
                if (weapon.Flags.TestFlag(WeaponFlags.Continuous)) Note("continuous");
                if (weapon.Flags.TestFlag(WeaponFlags.RepeatFire)) Note("repeat fire");
                if (weapon.Flags.TestFlag(WeaponFlags.CanCharge)) Note("chargeable");
                if (weapon.Flags.TestFlag(WeaponFlags.RicochetUncharged)
                    || weapon.Flags.TestFlag(WeaponFlags.RicochetCharged)) Note("ricochets");
                if (weapon.Flags.TestFlag(WeaponFlags.AoeUncharged)
                    || weapon.Flags.TestFlag(WeaponFlags.AoeCharged)) Note("area of effect");
                if (weapon.Flags.TestFlag(WeaponFlags.SelfDamageUncharged)
                    || weapon.Flags.TestFlag(WeaponFlags.SelfDamageCharged)) Note("can hurt the shooter");
                // Index 0 is the uncharged shot and index 1 the charged one.
                // Saying which is not a detail: every affliction in the game
                // sits on the charged entry, so a table that listed "Freeze"
                // without saying when read as "this weapon freezes people",
                // and a test that tapped the trigger could never reach it.
                var afflictions = new StringBuilder();
                for (int j = 0; j < weapon.Afflictions.Count; j++)
                {
                    if (weapon.Afflictions[j] != Affliction.None)
                    {
                        afflictions.Append(afflictions.Length > 0 ? ", " : "");
                        afflictions.Append(j == 0 ? "" : "charged: ");
                        afflictions.Append(weapon.Afflictions[j]);
                    }
                }
                text.AppendLine($"| {weapon.Beam} | {weapon.UnchargedDamage} | {weapon.MinChargeDamage} "
                    + $"| {weapon.ChargedDamage} | {weapon.HeadshotDamage} | {weapon.ChargedHeadshotDamage} "
                    + $"| {weapon.SplashDamage}/{weapon.ChargedSplashDamage} "
                    + $"| {(weapon.AmmoType == 0 ? "UA" : "missile")} | {weapon.AmmoCost}/{weapon.ChargeCost} "
                    + $"| {weapon.ShotCooldown} | {(afflictions.Length > 0 ? afflictions.ToString() : "-")} "
                    + $"| {(notes.Length > 0 ? notes.ToString() : "-")} |");
            }
            text.AppendLine();
            text.AppendLine();
            text.AppendLine("Affinity weapon per hunter (the one whose enhanced version it uses):");
            text.AppendLine();
            for (int i = 0; i < 7; i++)
            {
                text.AppendLine($"- {(Hunter)i}: {MphRead.Weapons.GetAffinityBeam((Hunter)i)}");
            }
            text.AppendLine();
        }

        private static void DamageRules(StringBuilder text)
        {
            text.AppendLine("## Damage multipliers, in the order the code applies them");
            text.AppendLine();
            text.AppendLine("| Rule | Effect | Where |");
            text.AppendLine("|---|---|---|");
            text.AppendLine("| Beam effectiveness vs the target | x0 / x0.5 / x1 / x2 | "
                + "`PlayerEntity.TakeDamage`, from `BeamEffectiveness[beam]`. Players are set to "
                + "Normal for every beam in `Spawn()`; **a player that never spawned has x0 for "
                + "everything and cannot be hurt at all** |");
            text.AppendLine("| Double damage pickup | x2, and *not* applied to Shock Coil | "
                + "`BeamProjectileEntity` |");
            text.AppendLine("| Prime Hunter | x1.5 | `BeamProjectileEntity` |");
            text.AppendLine("| **Imperialist without zoom** | **/2** | "
                + "`BeamProjectileEntity`: `if (weapon.Beam == Imperialist && !equip.Zoomed) damage /= 2` |");
            text.AppendLine("| Quadruple Damage cheat | x4 | `BeamProjectileEntity`, from settings.json. "
                + "Disabled automatically while connected to a server |");
            text.AppendLine("| Match damage level | "
                + $"x{Metadata.DamageLevels[0]} low / x{Metadata.DamageLevels[1]} medium / "
                + $"x{Metadata.DamageLevels[2]} high | `PlayerEntity.TakeDamage` |");
            text.AppendLine("| Headshot | uses the weapon's headshot damage instead | "
                + "`BeamProjectileEntity` |");
            text.AppendLine("| Friendly fire off, same team | x0 | `PlayerEntity.TakeDamage` |");
            text.AppendLine("| Weavel halfturret alive | damage is split between body and turret | "
                + "`PlayerEntity.TakeDamage` |");
            text.AppendLine("| Affinity weapon | the hunter uses entry `beam + 9`, which is a "
                + "different set of numbers entirely -- more damage and, for several weapons, an "
                + "affliction the plain version does not inflict | `PlayerEntity.TryEquipWeapon` |");
            text.AppendLine();
            text.AppendLine("Invulnerability windows: a hit sets a damage-invulnerability timer "
                + "(per hunter, `Values.DamageInvuln`), and spawning sets a spawn-invulnerability "
                + "timer. Both reject further damage until they run out.");
            text.AppendLine();
        }

        private static void Hunters(StringBuilder text)
        {
            text.AppendLine("## Hunters");
            text.AppendLine();
            text.AppendLine("| Hunter | energy tank | MP max health | MP ammo cap | alt form | "
                + "bombs | boost | alt attack |");
            text.AppendLine("|---|---|---|---|---|---|---|---|");
            for (int i = 0; i < 7; i++)
            {
                var hunter = (Hunter)i;
                PlayerValues values = Metadata.PlayerValues[i];
                bool bombs = hunter == Hunter.Samus || hunter == Hunter.Kanden || hunter == Hunter.Sylux;
                bool boost = hunter == Hunter.Samus;
                string alt = hunter switch
                {
                    Hunter.Samus => "Morph Ball",
                    Hunter.Kanden => "Stinglarva",
                    Hunter.Trace => "Triskelion",
                    Hunter.Sylux => "Lockjaw",
                    Hunter.Noxus => "Vhoscythe",
                    Hunter.Spire => "Dialanche",
                    Hunter.Weavel => "Halfturret",
                    _ => "-"
                };
                string altAttack = hunter switch
                {
                    Hunter.Trace => "cloak and lunge",
                    Hunter.Noxus => "spin attack",
                    Hunter.Spire => "slam",
                    Hunter.Weavel => "leaves a turret that shoots on its own",
                    _ => "bombs"
                };
                text.AppendLine($"| {hunter} | {values.EnergyTank} | {2 * values.EnergyTank - 1} "
                    + $"| {values.MpAmmoCap} | {alt} | {(bombs ? "yes" : "no")} "
                    + $"| {(boost ? "yes" : "no")} | {altAttack} |");
            }
            text.AppendLine();
            text.AppendLine("Health on spawn is `EnergyTank - 1`; the maximum in multiplayer is "
                + "`2 * EnergyTank - 1`, so a full pickup run doubles a hunter's effective health.");
            text.AppendLine();
        }

        private static void Movement(StringBuilder text)
        {
            text.AppendLine("## Movement, per hunter");
            text.AppendLine();
            text.AppendLine("Speeds are units per frame as the engine stores them (20.12 fixed "
                + "point converted to float on load).");
            text.AppendLine();
            text.AppendLine("| Hunter | walk cap | strafe cap | jump | biped gravity | alt gravity (air/ground) "
                + "| boost cap | boost charge (min-max) | alt radius |");
            text.AppendLine("|---|---|---|---|---|---|---|---|---|");
            for (int i = 0; i < 7; i++)
            {
                PlayerValues v = Metadata.PlayerValues[i];
                text.AppendLine($"| {(Hunter)i} | {Fixed.ToFloat(v.WalkSpeedCap):0.###} "
                    + $"| {Fixed.ToFloat(v.StrafeSpeedCap):0.###} | {Fixed.ToFloat(v.JumpSpeed):0.###} "
                    + $"| {Fixed.ToFloat(v.BipedGravity):0.####} "
                    + $"| {Fixed.ToFloat(v.AltAirGravity):0.####}/{Fixed.ToFloat(v.AltGroundGravity):0.####} "
                    + $"| {Fixed.ToFloat(v.BoostSpeedCap):0.###} | {v.BoostChargeMin}-{v.BoostChargeMax} "
                    + $"| {Fixed.ToFloat(v.AltColRadius):0.###} |");
            }
            text.AppendLine();
            text.AppendLine("- Morphing plays an animation and the form only changes when it ends "
                + "(`EnterAltForm` sets Morphing; `ProcessPlayer` applies `UpdateForm` on "
                + "`AnimFlags.Ended`). Unmorphing applies the change immediately.");
            text.AppendLine("- Alt form swaps the collision volume (`PlayerVolumes[hunter, 2]`), and "
                + "the position is shifted by the difference between the two volume centres.");
            text.AppendLine("- Boost is a charge-then-release: hold to build from `BoostChargeMin` to "
                + "`BoostChargeMax`, release to convert it into speed between `BoostSpeedMin` and "
                + "`BoostSpeedMax`.");
            text.AppendLine();
        }

        private static void States(StringBuilder text)
        {
            text.AppendLine("## States a player can be put into");
            text.AppendLine();
            text.AppendLine("| State | Cause | Duration | Effect |");
            text.AppendLine("|---|---|---|---|");
            text.AppendLine("| Frozen | Judicator (affinity version only) | 75 frames doubled; 15 "
                + "doubled if refrozen within 60 doubled | cannot act; the ice layer draws over the "
                + "hunter; animation frames stop advancing |");
            text.AppendLine("| Disrupted | Volt Driver (affinity) | 60 doubled | HUD distortion, "
                + "aim disrupted |");
            text.AppendLine("| Burning | Magmaul (affinity) | 150 doubled | damage over time, "
                + "attributed to whoever set the fire |");
            text.AppendLine("| Double damage | pickup | timer | x2 outgoing damage, Shock Coil "
                + "excepted; a visible effect is attached to the gun |");
            text.AppendLine("| Cloaked | pickup | timer | alpha drops towards invisible |");
            text.AppendLine("| Deathalt | pickup | timer | forced alt form, health drains, heavy "
                + "damage output |");
            text.AppendLine("| Halfturret | Weavel morphs | until unmorph or death | the turret is a "
                + "separate entity that shoots on its own; damage is split between it and the body, "
                + "and unmorphing gives its remaining health back to Weavel |");
            text.AppendLine("| Damage invulnerable | any hit | `Values.DamageInvuln` doubled | "
                + "further hits are rejected outright |");
            text.AppendLine("| Spawn invulnerable | spawning | timer | hits are rejected unless the "
                + "damage carries `IgnoreInvuln` or `Death` |");
            text.AppendLine();
        }

        private static void SpawnRules(StringBuilder text)
        {
            text.AppendLine("## Spawning and respawning");
            text.AppendLine();
            text.AppendLine("`PlayerProcess.GetRespawnPoint` picks a point by these rules, in order:");
            text.AppendLine();
            text.AppendLine("1. Consider at most 25 spawn points. Skip any that is inactive, still "
                + "on cooldown, or (on the very first frame) flagged by availability.");
            text.AppendLine("2. In Capture, skip points belonging to the other team.");
            text.AppendLine("3. A point is *valid* only if every living player is at least 10 units "
                + "away. Among the valid ones, the choice rotates with the frame counter.");
            text.AppendLine("4. If none is valid, take the one furthest from any living player.");
            text.AppendLine("5. If even that is unavailable -- every point on cooldown, which happens "
                + "with more players than the map was drawn for -- take any active point. Without "
                + "this last step the player simply does not spawn and waits at the origin.");
            text.AppendLine();
            text.AppendLine("The chosen point goes on a cooldown of 2 frames doubled, so a crowd "
                + "cannot all land on the same one.");
            text.AppendLine();
            text.AppendLine("A dead player waits on `_respawnTimer`; it may spawn early by holding "
                + "fire. Health on spawn is `EnergyTank - 1`. **`Spawn()` is also what fills in "
                + "`BeamEffectiveness`** -- a player that reaches the map without it takes zero "
                + "damage from every beam in the game.");
            text.AppendLine();
        }

        private static void Modes(StringBuilder text)
        {
            text.AppendLine("## Match modes");
            text.AppendLine();
            text.AppendLine("| Mode | Scored on | Second column on the scoreboard |");
            text.AppendLine("|---|---|---|");
            text.AppendLine("| Battle / Battle Teams | points (a kill is +1, dying is -1) | deaths |");
            text.AppendLine("| Survival / Survival Teams | time alive | deaths; running out of lives "
                + "puts a player out of the game |");
            text.AppendLine("| Capture | octoliths taken | kills |");
            text.AppendLine("| Bounty / Bounty Teams | octoliths delivered | kills |");
            text.AppendLine("| Nodes / Nodes Teams | points from held nodes | kills |");
            text.AppendLine("| Defender / Defender Teams | time holding the node | kills |");
            text.AppendLine("| Prime Hunter | time spent as the prime hunter | kills; the prime "
                + "hunter deals x1.5 damage and is shown to everyone |");
            text.AppendLine();
            text.AppendLine("A match ends on the point goal or the time limit, whichever comes "
                + "first. Team play merges the per-player tallies into two team tallies, and with "
                + "friendly fire off a shot at a team-mate does nothing at all.");
            text.AppendLine();
        }

        private static void World(StringBuilder text)
        {
            text.AppendLine("## World interactions");
            text.AppendLine();
            text.AppendLine("| Thing | Behaviour |");
            text.AppendLine("|---|---|");
            text.AppendLine("| Jump pad | launches whatever touches it along a fixed vector; this is "
                + "the one place a player legitimately covers a lot of ground in a few frames |");
            text.AppendLine("| Teleporter | moves the player to the linked pad, optionally forcing "
                + "alt form on arrival |");
            text.AppendLine("| Door / force field | opens on contact or on a weapon of the right "
                + "colour; locked doors ignore everything else |");
            text.AppendLine("| Kill height | a room-wide floor: below it the player dies. This is "
                + "what most \"random deaths\" in a fast match actually are |");
            text.AppendLine("| Lava and hazard volumes | set the player on fire while standing in "
                + "them, except for Spire, who is immune |");
            text.AppendLine("| Morph camera | a volume that forces the camera behind a morphed "
                + "player, and blocks unmorphing while inside |");
            text.AppendLine("| Item spawner | respawns its item on a timer once taken |");
            text.AppendLine();
        }

        private static void Bots(StringBuilder text)
        {
            text.AppendLine("## Bots");
            text.AppendLine();
            text.AppendLine("A bot is an ordinary player whose `Controls` are written by "
                + "`PlayerAi.ProcessInput` instead of by a keyboard. That is the whole of the "
                + "difference, and it is why a networked player can reuse the same surface: "
                + "relayed input is simply a third writer of the same buttons.");
            text.AppendLine();
            text.AppendLine("| Piece | What it does |");
            text.AppendLine("|---|---|");
            text.AppendLine("| `PlayerEntity.IsBot` | marks the slot as AI-driven. "
                + "`Scene.AddPlayer` sets it on every player after the first, which is right for a "
                + "local match and wrong for a networked one -- the AI would overwrite relayed "
                + "input, so a networked session clears it on every slot |");
            text.AppendLine("| `BotLevel` (0-2) | difficulty; clamped and used to index reaction "
                + "and accuracy tables |");
            text.AppendLine("| `AiPersonality` | per-hunter behaviour trees loaded from the ROM's "
                + "own data, one set per hunter and encounter. `AiPersonalityData1` nodes hold "
                + "conditions and the function ids to run |");
            text.AppendLine("| `AiData.Process()` | run once per frame per bot from "
                + "`Scene.UpdateScene`, but only while the bot is alive |");
            text.AppendLine("| `UpdateExecutionPath` / `Execute` | walks the tree and dispatches "
                + "`Func24Id` to the behaviour functions -- move, aim, fire, morph, use the alt "
                + "attack, pick a weapon |");
            text.AppendLine("| Weapon choice | prefers the hunter's affinity weapon "
                + "(`Weapons.AffinityWeapons[hunter]`) and zooms when it holds a weapon that can |");
            text.AppendLine("| `AiFlags3` | the spawn/despawn handshake: one bit asks for the spawn "
                + "effect and sound, another marks the bot as despawned |");
            text.AppendLine();
            text.AppendLine("For testing, `NetTestScript` replaces the AI entirely: it writes the "
                + "same `Controls`, but to a fixed script rather than a behaviour tree, so two "
                + "machines can be asked to do the same thing at the same moment and compared.");
            text.AppendLine();
        }

        private static void Networking(StringBuilder text)
        {
            text.AppendLine("## How multiplayer works here");
            text.AppendLine();
            text.AppendLine("This is not the DS Wi-Fi protocol and cannot talk to real hardware or "
                + "an emulator. It connects MphRead instances to each other.");
            text.AppendLine();
            text.AppendLine("| Piece | Rule |");
            text.AppendLine("|---|---|");
            text.AppendLine("| Server | a relay with no game files: it assigns slots, keeps the "
                + "match clock and the map rotation, and forwards packets. It never simulates |");
            text.AppendLine("| Authority | the first client to connect. It resolves damage, deaths "
                + "and scores for everybody |");
            text.AppendLine("| Position | owned by the player it belongs to. Each client publishes "
                + "its own position in every intent and everyone else follows it, including the "
                + "authority. Two simulations of one player fighting over a position is what "
                + "produced rubber-banding |");
            text.AppendLine("| Input | relayed to every client, not only the authority. Input is "
                + "what makes a player fire, morph, lay a bomb or swing an alt attack; clients that "
                + "received only positions drew opponents gliding in silence |");
            text.AppendLine("| One-frame presses | carried as an 8-frame history of rising edges, "
                + "because a press exists in exactly one packet and UDP loses packets. Edges are "
                + "taken *only* from that history: deriving them from the button level as well "
                + "applied each press twice, which for a toggle means never |");
            text.AppendLine("| Snapshot | the authority's view of every player: health, score, "
                + "form, weapon, zoom, and a damage record. Sent every frame |");
            text.AppendLine("| Damage | resolved only by the authority; every other client throws "
                + "away locally-resolved hits. The authority stamps each hit with a counter, and "
                + "victims replay the *difference* in that counter, so several hits between two "
                + "snapshots are all accounted for |");
            text.AppendLine("| Score | carried in the snapshot. Counting locally worked only for "
                + "whoever had been present since the first kill |");
            text.AppendLine("| Remote smoothing | remote players ease toward their reported "
                + "position (35% of the gap per frame, 60% when it is wide) and only jump past 15 "
                + "units, so a lost burst glides instead of popping |");
            text.AppendLine("| Lag compensation | the authority rewinds every other player to "
                + "the snapshot frame the shooter had acknowledged, spawns the shot into that "
                + "world, and then walks it forward to the present one frame at a time. Bounded "
                + "at 24 frames (400 ms) of rewind and 64 frames of history. The authority's own "
                + "shots are rewound by zero: it already aims at the puppets it resolves "
                + "against |");
            text.AppendLine("| Slots | `PlayerEntity.SlotCapacity` (8). Every slot-indexed array is "
                + "sized from it |");
            text.AppendLine("| Map rotation | the server owns it; clients poll the match state and "
                + "load the new room, rebuilding every player slot and resetting the scores |");
            text.AppendLine("| Chat | T opens a line, the server stamps it with the sender's real "
                + "slot and name and relays it to everybody else, and the sender echoes its own. "
                + "Rate limited at the relay: three back to back, then one every two seconds. "
                + "Additive on the wire, so an older server simply drops it |");
            text.AppendLine();
        }

        private static void Items(StringBuilder text)
        {
            text.AppendLine("## Pickups");
            text.AppendLine();
            text.AppendLine("| Item | Effect |");
            text.AppendLine("|---|---|");
            text.AppendLine("| HealthSmall / HealthMedium / HealthBig | restores health |");
            text.AppendLine("| UASmall / UABig | universal ammo |");
            text.AppendLine("| MissileSmall / MissileBig | missile ammo |");
            text.AppendLine("| VoltDriver, Battlehammer, Imperialist, Judicator, Magmaul, ShockCoil "
                + "| grants the weapon and its ammo |");
            text.AppendLine("| DoubleDamage | x2 damage for a time, Shock Coil excepted |");
            text.AppendLine("| Cloak | invisibility for a time |");
            text.AppendLine("| Deathalt | forced alt form, drains health, heavy damage |");
            text.AppendLine("| OmegaCannon | one-shot kill weapon |");
            text.AppendLine();
            text.AppendLine("A player killed in multiplayer drops ammo of the type its killer's "
                + "weapon uses.");
            text.AppendLine();
        }
    }
}
